#if !canImport(ObjectiveC)
import XCTest

extension Blake2bTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__Blake2bTests = [
        ("testSimpleApi", testSimpleApi),
        ("testStreamingApi", testStreamingApi),
    ]
}

extension Blake2bpTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__Blake2bpTests = [
        ("testSimpleApi", testSimpleApi),
        ("testStreamingApi", testStreamingApi),
    ]
}

extension Blake2sTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__Blake2sTests = [
        ("testSimpleApi", testSimpleApi),
        ("testStreamingApi", testStreamingApi),
    ]
}

extension Blake2spTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__Blake2spTests = [
        ("testSimpleApi", testSimpleApi),
        ("testStreamingApi", testStreamingApi),
    ]
}

extension Blake2xbTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__Blake2xbTests = [
        ("testSimpleApi", testSimpleApi),
        ("testStreamingApi", testStreamingApi),
    ]
}

extension Blake2xsTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__Blake2xsTests = [
        ("testSimpleApi", testSimpleApi),
        ("testStreamingApi", testStreamingApi),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(Blake2bTests.__allTests__Blake2bTests),
        testCase(Blake2bpTests.__allTests__Blake2bpTests),
        testCase(Blake2sTests.__allTests__Blake2sTests),
        testCase(Blake2spTests.__allTests__Blake2spTests),
        testCase(Blake2xbTests.__allTests__Blake2xbTests),
        testCase(Blake2xsTests.__allTests__Blake2xsTests),
    ]
}
#endif
