#if !canImport(ObjectiveC)
import XCTest

extension Blake2bTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__Blake2bTests = [
        ("testSimpleApi", testSimpleApi),
        ("testStreamingApi", testStreamingApi),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(Blake2bTests.__allTests__Blake2bTests),
    ]
}
#endif
