name: Publish CocoaPods package
on:
  release:
    types: [created]
jobs:
  publish:
    runs-on: macOS-13
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Select Xcode
        run: sudo xcode-select -s /Applications/Xcode_14.3.1.app
      - name: Set release version
        run: sed -i '' "s|[[:blank:]]*s\.version[[:blank:]].*|s.version = '${VERSION}'|g" *.podspec
        env: 
          VERSION: ${{ github.event.release.tag_name }}
      - name: Publish Pod
        run: pod trunk push --allow-warnings
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
        
