name: Build & Tests
on: [push, pull_request]
jobs:
  apple:
    strategy:
      matrix:
        tests: 
          - xcode: '14.2'
            machine: macos-12
          - xcode: '14.3.1'
            machine: macos-13
    runs-on: ${{ matrix.tests.machine }}
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Select Xcode
        run: sudo xcode-select -s /Applications/Xcode_${{ matrix.tests.xcode }}.app
      - name: Build and Test SPM
        run: swift test
      - name: Update Cocoa Pods repo
        run: pod repo update
      - name: Build and Test CocoaPods
        run: pod lib lint --allow-warnings --fail-fast
  linux:
    strategy:
      matrix:
        swift: ['5.4', '5.6', '5.8']
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    container:
      image: swift:${{ matrix.swift }}
      options: --cap-add=SYS_PTRACE --security-opt seccomp=unconfined --security-opt apparmor=unconfined
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build and Test
        run: swift test
